### ISSUE TITLE
IndieGala - only process opened keys

### ISSUE THREAD

**Issue by reyaz006** [LiteOnE/Steam-Scripts#16]
I only open keys I'm going to activate myself, and prefer keeping keys I didn't activate locked. This way I'd see them right away when I need them later.

Could there be some option to only process keys that were opened by user in the current bundle?

**Comment by LiteOnE** [comment]
Hello, I marked it as low priority, since I'm not sure if it's a big deal, since you can store unused/reserved keys in a file or so.

**Comment by reyaz006** [comment]
It's not a big deal, right. Thanks.

**Comment by LiteOnE** [comment]
Closed, because the enhancement have insignificant impact
