### ISSUE TITLE
Badge Autocraft 2 [2.6] is not working.

### ISSUE THREAD

**Issue by Eiion** [LiteOnE/Steam-Scripts#19]
The script isn't working, it only gives the error pop-up message "Badge Autocraft script can't read settings values! It may occur because of the script got an update. Please set up script's settings again, since they are cleared now"

**Comment by LiteOnE** [comment]
@Eiion so it says, that you should check your settings

**Comment by Eiion** [comment]
Be more descriptive. Steam settings? The script settings? I checked both and both seemed ok to me.

**Comment by LiteOnE** [comment]
@Eiion It clearly says, that you should set up your script's settings. You seem to forget to save them.
