### ISSUE TITLE
Batch Keys Activator - Autoselect "I agree to the terms"

### ISSUE THREAD

**Issue by lenisko** [LiteOnE/Steam-Scripts#21]
Hi there!

Can you add an option to auto-select `I agree to the terms of the Steam Subscriber Agreement...` 
this should be pretty simple:
```
if (agree_terms_option) {
    document.getElementById("accept_ssa").checked = true;
}
```

Thanks for plugin btw! a big time-saver.

**Comment by LiteOnE** [comment]
I didn't add auto-select intentionally respecting SSA. But I think I'll add that as a setting in menu. Also move `AutoActivate` there too

**Comment by lenisko** [comment]
Yes, option to enabled or disabled it would be sane idea.

**Comment by LiteOnE** [comment]
https://github.com/LiteOnE/Steam-Scripts/commit/f46c93ae39cb3725db6947e9aa52dd86de67683f
