### ISSUE TITLE
not really an issue

### ISSUE THREAD

**Issue by witherbosss** [LiteOnE/Steam-Scripts#32]
this isn't an actual issue but is it possible to make your own preset(for "animated" avatar?

**Comment by LiteOnE** [comment]
It is possible. Add your preset to this array https://github.com/LiteOnE/Steam-Scripts/blob/master/Animated-Avatar/Animated-Avatar.user.js#L26 
[appid, number_of_images, [ thumbnails ]]
I guess you can leave thumbnails array empty
