### ISSUE TITLE
Batch Keys Activator stopped working

### ISSUE THREAD

**Issue by psydex** [LiteOnE/Steam-Scripts#9]
As of 31/01 can't press "**Continue**"
![batch](https://user-images.githubusercontent.com/5594251/35683494-cebeffb0-076c-11e8-8a7a-84aee4f4d65a.gif)

Using latest Firefox with Tampermonkey

**Comment by LiteOnE** [comment]
Yep, it seems Steam has updated something. I'll fix this asap

**Comment by LiteOnE** [comment]
Ah nop, it's I broke the script with its last update to grab keys from the url (...?key=key1,key1,...,keyN)
Fixed https://github.com/LiteOnE/Steam-Scripts/commit/4f452c3beb6f5c0fa287fc17ebe2e6d8e09578b2
